version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CoinTrackerDB
    ports:
      - "5432:5432"
  
  app:
    build: .
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=CoinTrackerDB"
    ports:
      - "5091:5000"